title: "Crawler"
description: Enter a web page address, you can use this web crawler to crawl and
  output the data
icon: ":carbon:search:"

inputs_def:
  - handle: url
    description: "要搜索的网页 URL"
    json_schema:
      type: string
      nullable: true
    nullable: false

outputs_def:
  - handle: content
    description: "搜索或处理后的内容结果"
    json_schema:
      type: string

executor:
  name: nodejs
  options:
    entry: main.ts
    spawn: false
